package skywolf46.devain.core.api.exceptions

class AlreadyUsedException : RuntimeException("This trigger is already used.")